pipeline {
    agent any
    
    stages{
        stage('build'){
            steps{
                sh '''
                    echo "This is BUILD Stage"
                    echo "Listing Workspace"
                    ls ${WORKSPACE}
                '''
            }
        }
        
        stage('deploy'){
            steps {
                sh '''
                    echo "This is DEPLOY stage"
                '''
            }
        }
    }
}
